name: "Release by Tag"

on:
  push:
    tags:
      - v\d+\.\d+\.\d+
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: natsuneko-laboratory/get-meta-from-glob@main
        with:
          patterns: |
            Assets/NatsunekoLaboratory/AnimatorControllerToolPostProcessing/**/*.*
          output: ./MetaList

      - run: |
          mkdir ./dist
      - uses: natsuneko-laboratory/create-unitypackage@main
        with:
          meta: ./MetaList
          output: dist/AnimatorControllerToolPostProcessing.unitypackage

      - uses: noelware/s3-action@1.2.0
        with:
          directories: ./dist
          access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          use-wasabi: true
          bucket: archive.mochizuki.moe
          
