name: "Release VPMPackage by Pushing Tag"

on:
  push:
    tags:
      - v\d+\.\d+\.\d+
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      identifier: ${{ steps.vars.outputs.identifier }}
      name: ${{ steps.vars.outputs.name }}
      version: ${{ steps.vars.outputs.version }}
    steps:
      - id: vars
        env:
          NAME: AnimatorControllerToolPostProcessing
          IDENTIFIER: cat.natsuneko.animator-controller-tool-postprocessing
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///' | sed -e 's/refs\/heads\///')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "identifier=$IDENTIFIER" >> $GITHUB_OUTPUT

  packaging:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false

      - run: |
          mkdir ./dist
      - uses: natsuneko-laboratory/create-vpmpackage@v1.0.0
        with:
          package: Assets/NatsunekoLaboratory/${{ needs.setup.outputs.name }}/package.json
          output: dist/${{ needs.setup.outputs.identifier }}-${{ needs.setup.outputs.version }}.zip

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.setup.outputs.name }}
          path: ./dist